// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WisApi.Data;

#nullable disable

namespace WisApi.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240520180500_AddComment")]
    partial class AddComment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WisApi.Models.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WisApi.Models.PostModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4088),
                            IpAdress = "192.168.1.1",
                            IsAnonymous = false,
                            Text = "Welcome to the forum! Introduce yourself here. What's your name and what brings you to our forum?",
                            Title = "Forum Introduction",
                            TopicId = 1,
                            UserId = "user1",
                            UserName = "User One"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4090),
                            IpAdress = "192.168.1.1",
                            IsAnonymous = false,
                            Text = "What's on your mind today?",
                            Title = "Daily Thoughts",
                            TopicId = 1,
                            UserId = "user1",
                            UserName = "User One"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4096),
                            IpAdress = "192.168.1.1",
                            IsAnonymous = false,
                            Text = "Share your favorite hobbies and interests. What hobbies or interests do you enjoy in your free time?",
                            Title = "Hobbies and Interests",
                            TopicId = 1,
                            UserId = "user1",
                            UserName = "User One"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4097),
                            IpAdress = "192.168.1.1",
                            IsAnonymous = false,
                            Text = "How do you manage your time effectively? What strategies do you use to manage your time effectively?",
                            Title = "Time Management",
                            TopicId = 1,
                            UserId = "user1",
                            UserName = "User One"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4099),
                            IpAdress = "192.168.1.1",
                            IsAnonymous = false,
                            Text = "What are your goals for this year? What are your main goals for this year and how do you plan to achieve them?",
                            Title = "Yearly Goals",
                            TopicId = 1,
                            UserId = "user1",
                            UserName = "User One"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4439),
                            IpAdress = "192.168.1.2",
                            IsAnonymous = false,
                            Text = "The funniest memes of 2024. Which meme has made you laugh the most this year?",
                            Title = "Top Memes of 2024",
                            TopicId = 2,
                            UserId = "user2",
                            UserName = "User Two"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4441),
                            IpAdress = "192.168.1.2",
                            IsAnonymous = false,
                            Text = "Trending hashtags and their origins. What's your favorite trending hashtag and its story?",
                            Title = "Trending Hashtags",
                            TopicId = 2,
                            UserId = "user2",
                            UserName = "User Two"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4443),
                            IpAdress = "192.168.1.2",
                            IsAnonymous = false,
                            Text = "Internet challenges: Are they safe? Have you tried any internet challenges? Were they safe?",
                            Title = "Internet Challenges",
                            TopicId = 2,
                            UserId = "user2",
                            UserName = "User Two"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4445),
                            IpAdress = "192.168.1.2",
                            IsAnonymous = false,
                            Text = "Viral videos: What makes them so popular? What elements do you think contribute to a video going viral?",
                            Title = "Viral Videos",
                            TopicId = 2,
                            UserId = "user2",
                            UserName = "User Two"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(4446),
                            IpAdress = "192.168.1.2",
                            IsAnonymous = false,
                            Text = "Online communities you should join. What online communities do you recommend joining and why?",
                            Title = "Online Communities",
                            TopicId = 2,
                            UserId = "user2",
                            UserName = "User Two"
                        });
                });

            modelBuilder.Entity("WisApi.Models.TopicModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3935),
                            Description = "Discuss anything and everything under the sun",
                            IpAdress = "192.168.1.1",
                            IsAnonymous = false,
                            Title = "General",
                            UserId = "user1",
                            UserName = "User One"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3940),
                            Description = "Explore the latest trends and memes from the web",
                            IpAdress = "192.168.1.2",
                            IsAnonymous = false,
                            Title = "Internet Culture",
                            UserId = "user2",
                            UserName = "User Two"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3941),
                            Description = "Share tips, reviews, and news about your favorite games",
                            IpAdress = "192.168.1.3",
                            IsAnonymous = false,
                            Title = "Games",
                            UserId = "user3",
                            UserName = "User Three"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3943),
                            Description = "Ask questions and get answers from the community",
                            IpAdress = "192.168.1.4",
                            IsAnonymous = false,
                            Title = "Q&As",
                            UserId = "user4",
                            UserName = "User Four"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3944),
                            Description = "Stay updated with the latest tech news and gadgets",
                            IpAdress = "192.168.1.5",
                            IsAnonymous = false,
                            Title = "Technology",
                            UserId = "user5",
                            UserName = "User Five"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3945),
                            Description = "Dive into discussions about music, celebrities, and more",
                            IpAdress = "192.168.1.6",
                            IsAnonymous = false,
                            Title = "Pop Culture",
                            UserId = "user6",
                            UserName = "User Six"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3946),
                            Description = "Discuss the latest movies and TV shows",
                            IpAdress = "192.168.1.7",
                            IsAnonymous = false,
                            Title = "Movie & TV",
                            UserId = "user7",
                            UserName = "User Seven"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3948),
                            Description = "Engage in discussions about current political events",
                            IpAdress = "192.168.1.8",
                            IsAnonymous = false,
                            Title = "Politics",
                            UserId = "user8",
                            UserName = "User Eight"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3950),
                            Description = "Share insights and news about the business world",
                            IpAdress = "192.168.1.9",
                            IsAnonymous = false,
                            Title = "Business",
                            UserId = "user9",
                            UserName = "User Nine"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 5, 20, 18, 5, 0, 120, DateTimeKind.Utc).AddTicks(3952),
                            Description = "Discuss your favorite anime series and movies",
                            IpAdress = "192.168.1.10",
                            IsAnonymous = false,
                            Title = "Anime",
                            UserId = "user10",
                            UserName = "User Ten"
                        });
                });

            modelBuilder.Entity("WisApi.Models.CommentModel", b =>
                {
                    b.HasOne("WisApi.Models.PostModel", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("WisApi.Models.PostModel", b =>
                {
                    b.HasOne("WisApi.Models.TopicModel", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WisApi.Models.PostModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("WisApi.Models.TopicModel", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
