/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ForumImport } from './routes/forum'
import { Route as LoginImport } from './routes/Login'
import { Route as IndexImport } from './routes/index'
import { Route as UserUserNameImport } from './routes/user/$userName'
import { Route as ForumTopicIndexImport } from './routes/forum/$topic/index'
import { Route as ForumTopicPostIdImport } from './routes/forum/$topic/$postId'

// Create/Update Routes

const ForumRoute = ForumImport.update({
  path: '/forum',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserUserNameRoute = UserUserNameImport.update({
  path: '/user/$userName',
  getParentRoute: () => rootRoute,
} as any)

const ForumTopicIndexRoute = ForumTopicIndexImport.update({
  path: '/$topic/',
  getParentRoute: () => ForumRoute,
} as any)

const ForumTopicPostIdRoute = ForumTopicPostIdImport.update({
  path: '/$topic/$postId',
  getParentRoute: () => ForumRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/forum': {
      preLoaderRoute: typeof ForumImport
      parentRoute: typeof rootRoute
    }
    '/user/$userName': {
      preLoaderRoute: typeof UserUserNameImport
      parentRoute: typeof rootRoute
    }
    '/forum/$topic/$postId': {
      preLoaderRoute: typeof ForumTopicPostIdImport
      parentRoute: typeof ForumImport
    }
    '/forum/$topic/': {
      preLoaderRoute: typeof ForumTopicIndexImport
      parentRoute: typeof ForumImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  ForumRoute.addChildren([ForumTopicPostIdRoute, ForumTopicIndexRoute]),
  UserUserNameRoute,
])

/* prettier-ignore-end */
